services:
  backend:
    image: eclipse-temurin:21-jdk
    container_name: jackso-backend
    working_dir: /app
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - ./backend/.gradle:/home/gradle/.gradle
    command: ["sh", "-c", "chmod +x ./gradlew && ./gradlew bootRun"]
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - db

  frontend:
    image: node:20-alpine
    container_name: jackso-frontend
    working_dir: /app
    ports:
      - "5173:5173"
      - "24678:24678"    # Vite HMR port
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["sh", "-c", "npm install && npm run dev -- --mode dev --host 0.0.0.0 --port 5173"]
    environment:
      VITE_API_URL: http://localhost:8080
    stdin_open: true
    tty: true
    depends_on:
      - backend
