version: "3.8"
services:
  db:
    image: postgres:16
    container_name: sq-db-local
    environment:
      POSTGRES_USER: jackso
      POSTGRES_PASSWORD: jackso123
      POSTGRES_DB: jackso_app
    ports:
      - "5432:5432"
    volumes:
      - pgdata_local:/var/lib/postgresql/data

volumes:
  pgdata_local:
