services:
  db:
    image: postgres:16
    container_name: jackso-db
    environment:
      POSTGRES_USER: jackso
      POSTGRES_PASSWORD: jackso123
      POSTGRES_DB: jackso_app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile  # Assumes fat jar build Dockerfile
    container_name: jackso-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile  # Assumes multi-stage Dockerfile: Vite build + Nginx
    container_name: jackso-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata:
