services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: jackso
      POSTGRES_PASSWORD: jackso123
      POSTGRES_DB: jackso_app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - db

volumes:
  pgdata:
