
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: jackso-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: jackso-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
