services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: jackso
      POSTGRES_PASSWORD: jackso123
      POSTGRES_DB: jackso_app
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports: ["8080:8080"]
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports: ["80:80"]
    depends_on:
      - backend

volumes:
  pgdata:
