spring:
  datasource:
    url: jdbc:postgresql://db:5432/jackso_app
    username: jackso
    password: jackso123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none    # lock down schema changes
    show-sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration
