spring:
  datasource:
    url: jdbc:postgresql://db:5432/jackso_app
    username: jackso
    password: jackso123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
